version: '3.3'
services:
  redis:
    image: redis
    container_name: go-redis-libSystem
    restart: always
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/conf:/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/logs:/logs
    command:
      - redis-server
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    container_name: go-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_library
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./data/postgres/config:/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./data/postgres/logs:/logs
  web:
    container_name: gin-server
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    depends_on:
      - postgres  # 确保 postgres 容器先启动
      - redis     # 如果 Gin 也需要 Redis，则可以加上
    volumes:
      # 这个共享卷是用来存放配置文件。
      - ./config/:/app/config/
      # 该共享卷用来存储日志文件
      - ./data/running/logs/:/app/logger/
      - ./data/uploads/:/app/uploads/
    ports:
      - '8080:8080'
