server:
  port: 8080
  # debug | release | test 运行环境
  level: debug

datasource:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: db_library
  ssl_mode: disable
  time_zone: Asia/Shanghai

redis:
  host: redis
  port: 6379
  password:
  data_base: 1

log:
  level: debug
  filepath: ./logger/systemLog.txt

jwt:
  name: Authorization # 请求头中携带jwt的key
  secret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl # jwt加密密钥
  expire: 86400 # jwt过期时间

