// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paperFieldNames          = builder.RawFieldNames(&Paper{}, true)
	paperRows                = strings.Join(paperFieldNames, ",")
	paperRowsExpectAutoSet   = strings.Join(stringx.Remove(paperFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	paperRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(paperFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	paperModel interface {
		Insert(ctx context.Context, data *Paper) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Paper, error)
		Update(ctx context.Context, data *Paper) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPaperModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Paper struct {
		Id            int64          `db:"id"`
		Title         string         `db:"title"`
		Author        string         `db:"author"`
		Department    sql.NullString `db:"department"`
		Year          int64          `db:"year"`
		Status        string         `db:"status"`
		DownloadTimes int64          `db:"download_times"`
		FilePath      string         `db:"file_path"`
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
)

func newPaperModel(conn sqlx.SqlConn) *defaultPaperModel {
	return &defaultPaperModel{
		conn:  conn,
		table: `"public"."paper"`,
	}
}

func (m *defaultPaperModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPaperModel) FindOne(ctx context.Context, id int64) (*Paper, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", paperRows, m.table)
	var resp Paper
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaperModel) Insert(ctx context.Context, data *Paper) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, paperRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Author, data.Department, data.Year, data.Status, data.DownloadTimes, data.FilePath)
	return ret, err
}

func (m *defaultPaperModel) Update(ctx context.Context, data *Paper) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, paperRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Title, data.Author, data.Department, data.Year, data.Status, data.DownloadTimes, data.FilePath)
	return err
}

func (m *defaultPaperModel) tableName() string {
	return m.table
}
