// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"LibSystem/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin/user",
				Handler: GetAllUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/user",
				Handler: AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/user",
				Handler: DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/user",
				Handler: EditPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/user/:id",
				Handler: GetUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/user/editPassword",
				Handler: UpdateUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/user/username",
				Handler: GetUserByNameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: LogoutHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
