// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
}

type AddUserResponse struct {
	Base
}

type Base struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteUserRequest struct {
	UserId int64 `path:"userId"`
}

type DeleteUserResponse struct {
	Base
}

type EditPasswordRequest struct {
	UserId      int64  `path:"userId"`
	NewPassword string `json:"newPassword"`
	OldPassword string `json:"oldPassword"`
}

type EditPasswordResponse struct {
	Base
}

type GetAllUserRequest struct {
}

type GetAllUserResponse struct {
	Base
	Data UserList `json:"data"`
}

type GetUserByIdRequest struct {
	Id int64 `path:"id"`
}

type GetUserByIdResponse struct {
	Base
	Data UserVO `json:"data"`
}

type GetUserByNameRequest struct {
	Username string `form:"username"`
}

type GetUserByNameResponse struct {
	Base
	Data UserVO `json:"data"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Base
	Data LoginResponseData `json:"data"`
}

type LoginResponseData struct {
	Token    string `json:"token"`
	UserID   string `json:"userId"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

type LogoutRequest struct {
}

type LogoutResponse struct {
	Base
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Base
}

type UpdateUserInfoRequest struct {
	UserId int64  `json:"userId"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Email  string `json:"email"`
}

type UpdateUserInfoResponse struct {
	Base
}

type UserList struct {
	List []UserVO `json:"list"`
}

type UserVO struct {
	UserId   int64  `json:"userId"`   //用户id
	Username string `json:"username"` //用户名
	Password string `json:"password"` //密码
	Role     string `json:"role"`     //角色
	Name     string `json:"name" `    //姓名
	Phone    string `json:"phone"`    //手机号
	Email    string `json:"email"`    //邮箱
}
